openapi: 3.0.0
info:
  title: Smultron API
  version: 1.0.0
  description: E-commerce API for products, categories, and orders management

servers:
  - url: /v1
    description: API Server (uses current domain)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        category:
          type: string
        article:
          type: string
        brand:
          type: string
        title:
          type: string
        subtitle:
          type: string
        price:
          type: number
        price_reduced:
          type: number
        description:
          type: array
          items:
            type: string
        tag:
          type: string
        index:
          type: integer
        stock:
          type: integer
        max_order:
          type: integer
        image:
          type: string
        images:
          type: array
          items:
            type: string

    Category:
      type: object
      properties:
        id:
          type: string
        brand:
          type: string
        title:
          type: string
        subtitle:
          type: string
        index:
          type: integer

    Order:
      type: object
      properties:
        id:
          type: string
        cart:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        order:
          $ref: '#/components/schemas/OrderDetails'
        total:
          type: number
        status:
          type: string
          enum: [pending, confirmed, shipped, delivered, cancelled]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CartItem:
      type: object
      required:
        - id
        - price
        - number
      properties:
        id:
          type: string
          description: Product ID
        price:
          type: number
          description: Price at time of order
        number:
          type: integer
          minimum: 1
          description: Quantity
        brand:
          type: string
        title:
          type: string
        subtitle:
          type: string
        category:
          type: string
        image:
          type: string

    OrderDetails:
      type: object
      required:
        - name
        - address
        - zip
        - city
        - phone
        - delivery
        - payment
      properties:
        name:
          type: string
        company:
          type: string
        address:
          type: string
        zip:
          type: string
        city:
          type: string
        phone:
          type: string
        delivery:
          type: string
          description: Delivery method (e.g., postnord, dhl)
        payment:
          type: string
          description: Payment method (e.g., swish, card)

    OrderItem:
      type: object
      description: Legacy order item format (deprecated)
      properties:
        productId:
          type: string
        quantity:
          type: integer
        price:
          type: number

    Error:
      type: object
      properties:
        error:
          type: string

paths:
  /auth/login:
    post:
      summary: Admin login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /catalog:
    get:
      summary: Get complete catalog (categories and products)
      description: Returns both categories and products in a single request for improved performance
      tags:
        - Catalog (Public)
      responses:
        '200':
          description: Complete catalog with categories and products
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

  /products:
    get:
      summary: List all products
      tags:
        - Products (Public)
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Create a new product
      tags:
        - Products (Admin)
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - category
                - brand
                - title
                - price
                - index
                - stock
                - image
              properties:
                category:
                  type: string
                article:
                  type: string
                brand:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                price:
                  type: number
                price_reduced:
                  type: number
                description:
                  type: array
                  items:
                    type: string
                tag:
                  type: string
                index:
                  type: integer
                stock:
                  type: integer
                max_order:
                  type: integer
                image:
                  type: string
                images:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products (Public)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a product
      tags:
        - Products (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                article:
                  type: string
                brand:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                price:
                  type: number
                price_reduced:
                  type: number
                description:
                  type: array
                  items:
                    type: string
                tag:
                  type: string
                index:
                  type: integer
                stock:
                  type: integer
                max_order:
                  type: integer
                image:
                  type: string
                images:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a product
      tags:
        - Products (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Product deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /categories:
    get:
      summary: List all categories
      tags:
        - Categories (Public)
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Create a new category
      tags:
        - Categories (Admin)
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - brand
                - title
                - index
              properties:
                brand:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                index:
                  type: integer
      responses:
        '201':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /categories/{id}:
    get:
      summary: Get category by ID
      tags:
        - Categories (Public)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a category
      tags:
        - Categories (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                brand:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                index:
                  type: integer
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a category
      tags:
        - Categories (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Category deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders:
    post:
      summary: Create a new order
      description: Creates a new order and decreases stock for ordered products
      tags:
        - Orders (Public)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cart
                - order
              properties:
                cart:
                  type: array
                  items:
                    $ref: '#/components/schemas/CartItem'
                order:
                  $ref: '#/components/schemas/OrderDetails'
            example:
              cart:
                - id: "labubu-labubu-1760164608843-7wfhd2wyn"
                  brand: "Pop Mart"
                  title: "Labubu"
                  subtitle: "Big into energy"
                  category: "labubu"
                  price: 599
                  number: 1
                  image: "/smultronet/graphics/temp/labubu-big-into-energy-1.jpg"
              order:
                name: "Bernhard"
                company: "ZwC"
                address: "Varmfrontsgatan 18"
                zip: "128 33"
                city: "Stockholm"
                phone: "0793513563"
                delivery: "postnord"
                payment: "swish"
      responses:
        '201':
          description: Order created successfully, stock decreased
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request or insufficient stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List all orders
      tags:
        - Orders (Admin)
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{id}:
    get:
      summary: Get order by ID
      tags:
        - Orders (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /orders/{id}/status:
    put:
      summary: Update order status
      tags:
        - Orders (Admin)
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [pending, confirmed, shipped, delivered, cancelled]
      responses:
        '200':
          description: Order status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
